version: '2'
services:
  datavol:
    image: centos:7.4.1708
    container_name: 'datavol'
    volumes:
      - ../nginx/conf:/etc/nginx/conf.d:ro
      - ../html:/var/www:ro
  nginx:
    image: nginx:1.13
    container_name: 'nginx'
    ports: 
      - '80:8080'
    volumes_from:
      - datavol